INFO 2023-09-11 10:18:58,068 autoreload 12604 15120 C:\DEV\EDU\Django\myproject\myproject\settings.py changed, reloading.
INFO 2023-09-11 10:18:58,741 autoreload 7536 15940 Watching for file changes with StatReloader
INFO 2023-09-11 10:19:08,578 autoreload 7536 15940 C:\DEV\EDU\Django\myproject\myproject\settings.py changed, reloading.
INFO 2023-09-11 10:19:09,277 autoreload 7208 4284 Watching for file changes with StatReloader
INFO 2023-09-11 10:19:15,096 views 7208 7552 Открыта страница about
INFO 2023-09-11 10:19:15,096 basehttp 7208 7552 "GET /about/ HTTP/1.1" 200 634
INFO 2023-09-11 10:19:15,521 views 7208 7552 Открыта главная страница
INFO 2023-09-11 10:19:15,521 basehttp 7208 7552 "GET / HTTP/1.1" 200 568
INFO 2023-09-11 10:19:15,919 views 7208 7552 Открыта страница about
INFO 2023-09-11 10:19:15,920 basehttp 7208 7552 "GET /about/ HTTP/1.1" 200 634
INFO 2023-09-11 10:19:16,268 views 7208 7552 Открыта главная страница
INFO 2023-09-11 10:19:16,269 basehttp 7208 7552 "GET / HTTP/1.1" 200 568
INFO 2023-09-11 10:19:30,690 autoreload 7208 4284 C:\DEV\EDU\Django\myproject\myproject\settings.py changed, reloading.
INFO 2023-09-11 10:19:31,387 autoreload 14832 952 Watching for file changes with StatReloader
INFO 2023-09-18 10:02:29,065 autoreload 10148 16432 Watching for file changes with StatReloader
INFO 2023-09-18 10:02:45,457 autoreload 5784 16332 Watching for file changes with StatReloader
ERROR 2023-09-18 10:03:24,865 log 5784 16412 Internal Server Error: /lesson3/orders/
Traceback (most recent call last):
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
TypeError: orders() missing 1 required positional argument: 'client'
ERROR 2023-09-18 10:03:24,866 basehttp 5784 16412 "GET /lesson3/orders/ HTTP/1.1" 500 64032
WARNING 2023-09-18 10:03:25,224 log 5784 16412 Not Found: /favicon.ico
WARNING 2023-09-18 10:03:25,224 basehttp 5784 16412 "GET /favicon.ico HTTP/1.1" 404 2549
INFO 2023-09-18 10:03:37,951 autoreload 5784 16332 C:\DEV\EDU\Django\myproject\lesson3app\urls.py changed, reloading.
INFO 2023-09-18 10:03:38,707 autoreload 16656 12116 Watching for file changes with StatReloader
INFO 2023-09-18 10:04:10,370 autoreload 6560 6224 Watching for file changes with StatReloader
INFO 2023-09-18 10:04:16,455 basehttp 6560 17256 "GET /lesson3/orders/1 HTTP/1.1" 200 5
INFO 2023-09-18 10:04:36,414 autoreload 6560 6224 C:\DEV\EDU\Django\myproject\lesson3app\urls.py changed, reloading.
INFO 2023-09-18 10:04:37,037 autoreload 16432 3228 Watching for file changes with StatReloader
INFO 2023-09-18 10:04:39,867 basehttp 16432 10540 "GET /lesson3/clientorders/1 HTTP/1.1" 200 5
INFO 2023-09-18 10:05:04,889 autoreload 16432 3228 C:\DEV\EDU\Django\myproject\lesson3app\urls.py changed, reloading.
INFO 2023-09-18 10:05:05,580 autoreload 14496 16536 Watching for file changes with StatReloader
INFO 2023-09-18 10:05:57,687 autoreload 14496 16536 C:\DEV\EDU\Django\myproject\lesson3app\views.py changed, reloading.
INFO 2023-09-18 10:05:58,410 autoreload 11296 11120 Watching for file changes with StatReloader
INFO 2023-09-18 10:07:41,607 autoreload 11296 11120 C:\DEV\EDU\Django\myproject\lesson3app\views.py changed, reloading.
INFO 2023-09-18 10:07:42,336 autoreload 16580 16904 Watching for file changes with StatReloader
INFO 2023-09-18 10:07:45,483 basehttp 16580 17324 "GET /lesson3/clientorders/1 HTTP/1.1" 200 169
INFO 2023-09-18 10:09:54,212 autoreload 16580 16904 C:\DEV\EDU\Django\myproject\lesson3app\views.py changed, reloading.
INFO 2023-09-18 10:09:54,882 autoreload 16628 16584 Watching for file changes with StatReloader
INFO 2023-09-18 10:10:34,201 autoreload 16628 16584 C:\DEV\EDU\Django\myproject\lesson3app\views.py changed, reloading.
INFO 2023-09-18 10:10:34,939 autoreload 16800 852 Watching for file changes with StatReloader
INFO 2023-09-18 10:10:45,941 autoreload 16800 852 C:\DEV\EDU\Django\myproject\lesson3app\views.py changed, reloading.
INFO 2023-09-18 10:10:46,810 autoreload 16884 16580 Watching for file changes with StatReloader
INFO 2023-09-18 10:12:14,705 autoreload 16884 16580 C:\DEV\EDU\Django\myproject\lesson3app\views.py changed, reloading.
INFO 2023-09-18 10:12:15,337 autoreload 13396 2444 Watching for file changes with StatReloader
ERROR 2023-09-18 10:14:24,724 log 13396 2532 Internal Server Error: /lesson3/clientorders/1
Traceback (most recent call last):
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
TypeError: client_orders() got an unexpected keyword argument 'client'
ERROR 2023-09-18 10:14:24,725 basehttp 13396 2532 "GET /lesson3/clientorders/1 HTTP/1.1" 500 64282
INFO 2023-09-18 10:14:46,013 autoreload 13396 2444 C:\DEV\EDU\Django\myproject\lesson3app\urls.py changed, reloading.
INFO 2023-09-18 10:14:46,764 autoreload 13208 16772 Watching for file changes with StatReloader
INFO 2023-09-18 10:14:47,723 basehttp 13208 7208 "GET /lesson3/clientorders/1 HTTP/1.1" 200 904
ERROR 2023-09-18 10:17:26,183 log 13208 7208 Internal Server Error: /lesson3/clientorders/1
Traceback (most recent call last):
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\DEV\EDU\Django\myproject\lesson3app\views.py", line 14, in client_orders
    return render(request, "lesson3app/client_orders.html", context)
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\template\defaulttags.py", line 238, in render
    nodelist.append(node.render_annotated(context))
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\template\defaulttags.py", line 193, in render
    values = list(values)
TypeError: 'ManyRelatedManager' object is not iterable
ERROR 2023-09-18 10:17:26,186 basehttp 13208 7208 "GET /lesson3/clientorders/1 HTTP/1.1" 500 123736
INFO 2023-09-18 10:18:28,523 basehttp 13208 7208 "GET /lesson3/clientorders/1 HTTP/1.1" 200 3619
INFO 2023-09-18 10:18:48,353 basehttp 13208 7208 "GET /lesson3/clientorders/1 HTTP/1.1" 200 3380
INFO 2023-09-18 10:18:58,780 basehttp 13208 7208 "GET /lesson3/clientorders/1 HTTP/1.1" 200 3490
INFO 2023-09-18 10:19:47,290 basehttp 13208 7208 "GET /lesson3/clientorders/1 HTTP/1.1" 200 10102
INFO 2023-09-18 10:20:05,614 basehttp 13208 7208 "GET /lesson3/clientorders/2 HTTP/1.1" 200 13618
INFO 2023-09-18 10:20:32,243 basehttp 13208 7208 "GET /lesson3/clientorders/2 HTTP/1.1" 200 13623
INFO 2023-09-18 10:20:53,500 basehttp 13208 7208 "GET /lesson3/clientorders/2 HTTP/1.1" 200 13683
INFO 2023-09-18 10:22:36,141 basehttp 13208 7208 "GET /lesson3/clientorders/2 HTTP/1.1" 200 14463
INFO 2023-09-18 10:22:51,235 basehttp 13208 7208 "GET /lesson3/clientorders/2 HTTP/1.1" 200 14393
INFO 2023-09-18 10:23:30,893 basehttp 13208 7208 "GET /lesson3/clientorders/2 HTTP/1.1" 200 14375
INFO 2023-09-18 10:29:22,395 autoreload 13208 16772 C:\DEV\EDU\Django\myproject\lesson3app\urls.py changed, reloading.
INFO 2023-09-18 10:29:23,166 autoreload 2840 9544 Watching for file changes with StatReloader
INFO 2023-09-18 10:31:43,920 autoreload 2840 9544 C:\DEV\EDU\Django\myproject\lesson3app\views.py changed, reloading.
INFO 2023-09-18 10:31:44,651 autoreload 5148 16704 Watching for file changes with StatReloader
INFO 2023-09-18 10:34:27,420 autoreload 5148 16704 C:\DEV\EDU\Django\myproject\lesson3app\views.py changed, reloading.
INFO 2023-09-18 10:34:28,086 autoreload 7452 2064 Watching for file changes with StatReloader
INFO 2023-09-18 10:34:51,726 autoreload 7452 2064 C:\DEV\EDU\Django\myproject\lesson3app\views.py changed, reloading.
INFO 2023-09-18 10:34:52,414 autoreload 12916 3956 Watching for file changes with StatReloader
INFO 2023-09-18 10:35:35,168 autoreload 12916 3956 C:\DEV\EDU\Django\myproject\lesson3app\views.py changed, reloading.
INFO 2023-09-18 10:35:35,872 autoreload 14192 3940 Watching for file changes with StatReloader
INFO 2023-09-18 10:37:28,800 autoreload 14192 3940 C:\DEV\EDU\Django\myproject\lesson3app\urls.py changed, reloading.
INFO 2023-09-18 10:37:29,518 autoreload 17184 5768 Watching for file changes with StatReloader
INFO 2023-09-18 10:38:06,616 autoreload 17184 5768 C:\DEV\EDU\Django\myproject\lesson3app\urls.py changed, reloading.
INFO 2023-09-18 10:38:07,355 autoreload 13836 16920 Watching for file changes with StatReloader
INFO 2023-09-18 10:38:16,076 basehttp 13836 12640 "GET /lesson3/clientgoods/2/7 HTTP/1.1" 200 257
INFO 2023-09-18 10:38:34,315 autoreload 13836 16920 C:\DEV\EDU\Django\myproject\lesson3app\views.py changed, reloading.
INFO 2023-09-18 10:38:35,085 autoreload 16532 3928 Watching for file changes with StatReloader
INFO 2023-09-18 10:38:35,870 basehttp 16532 14352 "GET /lesson3/clientgoods/2/7 HTTP/1.1" 200 258
INFO 2023-09-18 10:39:44,533 autoreload 16532 3928 C:\DEV\EDU\Django\myproject\lesson3app\views.py changed, reloading.
INFO 2023-09-18 10:39:45,763 autoreload 12956 16456 Watching for file changes with StatReloader
INFO 2023-09-18 10:39:46,638 basehttp 12956 5648 "GET /lesson3/clientgoods/2/7 HTTP/1.1" 200 258
INFO 2023-09-18 10:39:52,344 basehttp 12956 5648 "GET /lesson3/clientgoods/2/7 HTTP/1.1" 200 258
INFO 2023-09-18 10:39:56,964 basehttp 12956 5648 "GET /lesson3/clientgoods/2/7 HTTP/1.1" 200 258
INFO 2023-09-18 10:41:53,794 autoreload 12956 16456 C:\DEV\EDU\Django\myproject\lesson3app\views.py changed, reloading.
INFO 2023-09-18 10:41:54,763 autoreload 6080 6708 Watching for file changes with StatReloader
INFO 2023-09-18 10:41:57,935 basehttp 6080 4340 "GET /lesson3/clientgoods/2/7 HTTP/1.1" 200 258
INFO 2023-09-18 10:42:10,734 basehttp 6080 4340 "GET /lesson3/clientgoods/2/7 HTTP/1.1" 200 258
INFO 2023-09-18 10:42:26,158 autoreload 6080 6708 C:\DEV\EDU\Django\myproject\lesson3app\views.py changed, reloading.
INFO 2023-09-18 10:42:26,854 autoreload 17304 14160 Watching for file changes with StatReloader
INFO 2023-09-18 10:42:29,390 basehttp 17304 772 "GET /lesson3/clientgoods/2/7 HTTP/1.1" 200 258
INFO 2023-09-18 10:42:41,199 autoreload 17304 14160 C:\DEV\EDU\Django\myproject\lesson3app\views.py changed, reloading.
INFO 2023-09-18 10:42:41,919 autoreload 14268 6764 Watching for file changes with StatReloader
INFO 2023-09-18 10:42:42,754 basehttp 14268 16612 "GET /lesson3/clientgoods/2/7 HTTP/1.1" 200 258
INFO 2023-09-18 10:42:57,016 autoreload 14268 6764 C:\DEV\EDU\Django\myproject\lesson3app\views.py changed, reloading.
INFO 2023-09-18 10:42:57,764 autoreload 8184 16936 Watching for file changes with StatReloader
ERROR 2023-09-18 10:43:00,341 log 8184 464 Internal Server Error: /lesson3/clientgoods/2/7
Traceback (most recent call last):
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\DEV\EDU\Django\myproject\lesson3app\views.py", line 22, in client_goods
    orders = Order.objects.filter(client=client, date_ordered__range=(date(date_start), date(date_end))).order_by('date_ordered')
TypeError: 'datetime.date' object cannot be interpreted as an integer
ERROR 2023-09-18 10:43:00,343 basehttp 8184 464 "GET /lesson3/clientgoods/2/7 HTTP/1.1" 500 68771
INFO 2023-09-18 10:43:20,771 autoreload 8184 16936 C:\DEV\EDU\Django\myproject\lesson3app\views.py changed, reloading.
INFO 2023-09-18 10:43:21,624 autoreload 4848 16456 Watching for file changes with StatReloader
INFO 2023-09-18 10:43:24,038 basehttp 4848 2188 "GET /lesson3/clientgoods/2/7 HTTP/1.1" 200 258
INFO 2023-09-18 10:44:59,737 autoreload 4848 16456 C:\DEV\EDU\Django\myproject\lesson3app\views.py changed, reloading.
INFO 2023-09-18 10:45:00,554 autoreload 16936 16652 Watching for file changes with StatReloader
ERROR 2023-09-18 10:45:04,700 log 16936 11428 Internal Server Error: /lesson3/clientgoods/2/7
Traceback (most recent call last):
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\DEV\EDU\Django\myproject\lesson3app\views.py", line 18, in client_goods
    date_end = date.now()
AttributeError: type object 'datetime.date' has no attribute 'now'
ERROR 2023-09-18 10:45:04,701 basehttp 16936 11428 "GET /lesson3/clientgoods/2/7 HTTP/1.1" 500 68161
INFO 2023-09-18 10:45:22,192 autoreload 16936 16652 C:\DEV\EDU\Django\myproject\lesson3app\views.py changed, reloading.
INFO 2023-09-18 10:45:22,892 autoreload 13308 13916 Watching for file changes with StatReloader
INFO 2023-09-18 10:45:37,908 autoreload 13308 13916 C:\DEV\EDU\Django\myproject\lesson3app\views.py changed, reloading.
INFO 2023-09-18 10:45:38,656 autoreload 4640 12712 Watching for file changes with StatReloader
INFO 2023-09-18 10:45:43,581 basehttp 4640 13304 "GET /lesson3/clientgoods/2/7 HTTP/1.1" 200 258
INFO 2023-09-18 10:45:59,278 autoreload 4640 12712 C:\DEV\EDU\Django\myproject\lesson3app\views.py changed, reloading.
INFO 2023-09-18 10:46:00,003 autoreload 16944 11888 Watching for file changes with StatReloader
INFO 2023-09-18 10:46:01,847 basehttp 16944 6764 "GET /lesson3/clientgoods/2/7 HTTP/1.1" 200 258
INFO 2023-09-18 10:49:04,366 autoreload 16944 11888 C:\DEV\EDU\Django\myproject\lesson3app\views.py changed, reloading.
INFO 2023-09-18 10:49:05,075 autoreload 15700 872 Watching for file changes with StatReloader
INFO 2023-09-18 10:49:06,708 basehttp 15700 9956 "GET /lesson3/clientgoods/2/7 HTTP/1.1" 200 698
INFO 2023-09-18 10:49:18,973 basehttp 15700 9956 "GET /lesson3/clientgoods/9/7 HTTP/1.1" 200 604
INFO 2023-09-18 10:52:59,462 autoreload 10848 12708 Watching for file changes with StatReloader
INFO 2023-09-18 10:53:08,609 basehttp 10848 13500 "GET /lesson3/clientgoods/2/7 HTTP/1.1" 200 698
INFO 2023-09-21 11:20:06,339 autoreload 3100 16448 Watching for file changes with StatReloader
ERROR 2023-09-21 11:20:30,564 log 3100 2308 Internal Server Error: /lesson4/good/1
Traceback (most recent call last):
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
TypeError: good() got an unexpected keyword argument 'id'
ERROR 2023-09-21 11:20:30,566 basehttp 3100 2308 "GET /lesson4/good/1 HTTP/1.1" 500 64092
WARNING 2023-09-21 11:20:30,790 log 3100 2308 Not Found: /favicon.ico
WARNING 2023-09-21 11:20:30,790 basehttp 3100 2308 "GET /favicon.ico HTTP/1.1" 404 2657
INFO 2023-09-21 11:22:26,127 autoreload 3100 16448 C:\DEV\EDU\Django\myproject\lesson4app\views.py changed, reloading.
INFO 2023-09-21 11:22:26,830 autoreload 1724 18408 Watching for file changes with StatReloader
INFO 2023-09-21 11:22:29,460 basehttp 1724 12780 "GET /lesson4/good/1 HTTP/1.1" 200 1008
INFO 2023-09-21 11:23:04,263 autoreload 1724 18408 C:\DEV\EDU\Django\myproject\lesson4app\views.py changed, reloading.
INFO 2023-09-21 11:23:04,955 autoreload 6944 6784 Watching for file changes with StatReloader
INFO 2023-09-21 11:23:07,371 basehttp 6944 16040 "GET /lesson4/good/1 HTTP/1.1" 200 1008
INFO 2023-09-21 11:23:33,024 autoreload 6944 6784 C:\DEV\EDU\Django\myproject\lesson4app\views.py changed, reloading.
INFO 2023-09-21 11:23:33,743 autoreload 11724 17772 Watching for file changes with StatReloader
ERROR 2023-09-21 11:23:37,092 log 11724 13136 Internal Server Error: /lesson4/good/1
Traceback (most recent call last):
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\DEV\EDU\Django\myproject\lesson4app\views.py", line 17, in good
    form = GoodForm(name=good.name)
TypeError: BaseForm.__init__() got an unexpected keyword argument 'name'
ERROR 2023-09-21 11:23:37,094 basehttp 11724 13136 "GET /lesson4/good/1 HTTP/1.1" 500 68109
INFO 2023-09-21 11:23:54,467 autoreload 11724 17772 C:\DEV\EDU\Django\myproject\lesson4app\views.py changed, reloading.
INFO 2023-09-21 11:23:55,172 autoreload 15668 8612 Watching for file changes with StatReloader
ERROR 2023-09-21 11:23:57,045 log 15668 12284 Internal Server Error: /lesson4/good/1
Traceback (most recent call last):
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\DEV\EDU\Django\myproject\lesson4app\views.py", line 19, in good
    return render(request, "lesson4app/good.html", {'form': form})
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\template\base.py", line 1064, in render
    output = self.filter_expression.resolve(context)
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\template\base.py", line 715, in resolve
    obj = self.var.resolve(context)
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\template\base.py", line 847, in resolve
    value = self._resolve_lookup(context)
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\template\base.py", line 914, in _resolve_lookup
    current = current()
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\forms\utils.py", line 96, in as_div
    return self.render(self.template_name_div)
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\forms\utils.py", line 67, in render
    context = context or self.get_context()
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\forms\forms.py", line 322, in get_context
    top_errors = self.non_field_errors().copy()
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\forms\forms.py", line 358, in non_field_errors
    return self.errors.get(
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\forms\forms.py", line 196, in errors
    self.full_clean()
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\forms\forms.py", line 433, in full_clean
    self._clean_fields()
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\forms\forms.py", line 440, in _clean_fields
    value = bf.initial if field.disabled else bf.data
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\forms\boundfield.py", line 135, in data
    return self.form._widget_data_value(self.field.widget, self.html_name)
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\forms\forms.py", line 220, in _widget_data_value
    return widget.value_from_datadict(self.data, self.files, html_name)
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\forms\widgets.py", line 297, in value_from_datadict
    return data.get(name)
AttributeError: 'Good' object has no attribute 'get'
ERROR 2023-09-21 11:23:57,051 basehttp 15668 12284 "GET /lesson4/good/1 HTTP/1.1" 500 159104
INFO 2023-09-21 11:24:15,946 autoreload 15668 8612 C:\DEV\EDU\Django\myproject\lesson4app\views.py changed, reloading.
INFO 2023-09-21 11:24:16,745 autoreload 17148 9468 Watching for file changes with StatReloader
INFO 2023-09-21 11:25:59,452 autoreload 17148 9468 C:\DEV\EDU\Django\myproject\lesson4app\views.py changed, reloading.
INFO 2023-09-21 11:26:00,276 autoreload 15736 18352 Watching for file changes with StatReloader
INFO 2023-09-21 11:26:10,218 autoreload 15736 18352 C:\DEV\EDU\Django\myproject\lesson4app\views.py changed, reloading.
INFO 2023-09-21 11:26:11,076 autoreload 11172 10808 Watching for file changes with StatReloader
INFO 2023-09-21 11:26:16,681 basehttp 11172 14544 "GET /lesson4/good/1 HTTP/1.1" 200 1021
INFO 2023-09-21 11:27:33,795 autoreload 11172 10808 C:\DEV\EDU\Django\myproject\lesson4app\forms.py changed, reloading.
INFO 2023-09-21 11:27:34,561 autoreload 17404 7176 Watching for file changes with StatReloader
INFO 2023-09-21 11:27:36,810 basehttp 17404 7136 "GET /lesson4/good/1 HTTP/1.1" 200 883
ERROR 2023-09-21 11:27:41,236 log 17404 7136 Internal Server Error: /lesson4/good/1
Traceback (most recent call last):
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
sqlite3.IntegrityError: NOT NULL constraint failed: lesson4app_good.date_add

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\DEV\EDU\Django\myproject\lesson4app\views.py", line 14, in good
    good.save()
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\db\models\base.py", line 814, in save
    self.save_base(
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\db\models\base.py", line 877, in save_base
    updated = self._save_table(
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\db\models\base.py", line 990, in _save_table
    updated = self._do_update(
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\db\models\base.py", line 1054, in _do_update
    return filtered._update(values) > 0
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\db\models\query.py", line 1231, in _update
    return query.get_compiler(self.db).execute_sql(CURSOR)
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1984, in execute_sql
    cursor = super().execute_sql(result_type)
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\db\backends\utils.py", line 102, in execute
    return super().execute(sql, params)
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
django.db.utils.IntegrityError: NOT NULL constraint failed: lesson4app_good.date_add
ERROR 2023-09-21 11:27:41,242 basehttp 17404 7136 "POST /lesson4/good/1 HTTP/1.1" 500 149379
INFO 2023-09-21 11:29:18,808 autoreload 17404 7176 C:\DEV\EDU\Django\myproject\lesson4app\views.py changed, reloading.
INFO 2023-09-21 11:29:19,502 autoreload 2356 18004 Watching for file changes with StatReloader
INFO 2023-09-21 11:29:21,937 basehttp 2356 17132 "GET /lesson4/good/1 HTTP/1.1" 200 883
ERROR 2023-09-21 11:29:24,908 log 2356 17132 Internal Server Error: /lesson4/good/1
Traceback (most recent call last):
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\db\models\fields\__init__.py", line 1741, in to_python
    decimal_value = decimal.Decimal(value)
decimal.InvalidOperation: [<class 'decimal.ConversionSyntax'>]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\DEV\EDU\Django\myproject\lesson4app\views.py", line 16, in good
    good.save()
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\db\models\base.py", line 814, in save
    self.save_base(
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\db\models\base.py", line 877, in save_base
    updated = self._save_table(
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\db\models\base.py", line 990, in _save_table
    updated = self._do_update(
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\db\models\base.py", line 1054, in _do_update
    return filtered._update(values) > 0
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\db\models\query.py", line 1231, in _update
    return query.get_compiler(self.db).execute_sql(CURSOR)
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1984, in execute_sql
    cursor = super().execute_sql(result_type)
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1549, in execute_sql
    sql, params = self.as_sql()
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1947, in as_sql
    val = field.get_db_prep_save(val, connection=self.connection)
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\db\models\fields\__init__.py", line 1760, in get_db_prep_save
    self.to_python(value), self.max_digits, self.decimal_places
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\db\models\fields\__init__.py", line 1743, in to_python
    raise exceptions.ValidationError(
django.core.exceptions.ValidationError: ['“name1” value must be a decimal number.']
ERROR 2023-09-21 11:29:24,914 basehttp 2356 17132 "POST /lesson4/good/1 HTTP/1.1" 500 122776
INFO 2023-09-21 11:30:02,915 autoreload 2356 18004 C:\DEV\EDU\Django\myproject\lesson4app\views.py changed, reloading.
INFO 2023-09-21 11:30:03,609 autoreload 1844 10832 Watching for file changes with StatReloader
INFO 2023-09-21 11:30:05,736 basehttp 1844 16672 "GET /lesson4/good/1 HTTP/1.1" 200 883
ERROR 2023-09-21 11:30:08,776 log 1844 16672 Internal Server Error: /lesson4/good/1
Traceback (most recent call last):
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\DEV\EDU\Django\myproject\lesson4app\views.py", line 13, in good
    good.description = form.cleaned_data['description']
KeyError: 'description'
ERROR 2023-09-21 11:30:08,777 basehttp 1844 16672 "POST /lesson4/good/1 HTTP/1.1" 500 69893
INFO 2023-09-21 11:30:24,199 basehttp 1844 16672 "GET /lesson4/good/1 HTTP/1.1" 200 883
INFO 2023-09-21 11:31:11,372 autoreload 1844 10832 C:\DEV\EDU\Django\myproject\lesson4app\forms.py changed, reloading.
INFO 2023-09-21 11:31:12,057 autoreload 6016 6536 Watching for file changes with StatReloader
INFO 2023-09-21 11:31:16,131 basehttp 6016 6944 "GET /lesson4/good/1 HTTP/1.1" 200 1085
INFO 2023-09-21 11:31:30,604 autoreload 6016 6536 C:\DEV\EDU\Django\myproject\lesson4app\forms.py changed, reloading.
INFO 2023-09-21 11:31:31,321 autoreload 17972 17008 Watching for file changes with StatReloader
INFO 2023-09-21 11:31:33,930 basehttp 17972 1320 "GET /lesson4/good/1 HTTP/1.1" 200 1099
ERROR 2023-09-21 11:31:38,029 log 17972 1320 Internal Server Error: /lesson4/good/1
Traceback (most recent call last):
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
sqlite3.IntegrityError: NOT NULL constraint failed: lesson4app_good.date_add

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\DEV\EDU\Django\myproject\lesson4app\views.py", line 16, in good
    good.save()
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\db\models\base.py", line 814, in save
    self.save_base(
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\db\models\base.py", line 877, in save_base
    updated = self._save_table(
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\db\models\base.py", line 990, in _save_table
    updated = self._do_update(
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\db\models\base.py", line 1054, in _do_update
    return filtered._update(values) > 0
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\db\models\query.py", line 1231, in _update
    return query.get_compiler(self.db).execute_sql(CURSOR)
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1984, in execute_sql
    cursor = super().execute_sql(result_type)
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\db\backends\utils.py", line 102, in execute
    return super().execute(sql, params)
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
django.db.utils.IntegrityError: NOT NULL constraint failed: lesson4app_good.date_add
ERROR 2023-09-21 11:31:38,035 basehttp 17972 1320 "POST /lesson4/good/1 HTTP/1.1" 500 149486
INFO 2023-09-21 11:32:02,958 autoreload 17972 17008 C:\DEV\EDU\Django\myproject\lesson4app\views.py changed, reloading.
INFO 2023-09-21 11:32:03,650 autoreload 4064 1104 Watching for file changes with StatReloader
INFO 2023-09-21 11:32:05,338 basehttp 4064 13872 "GET /lesson4/good/1 HTTP/1.1" 200 1099
ERROR 2023-09-21 11:32:12,075 log 4064 13872 Internal Server Error: /lesson4/good/1
Traceback (most recent call last):
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
sqlite3.IntegrityError: NOT NULL constraint failed: lesson4app_good.date_add

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\DEV\EDU\Django\myproject\lesson4app\views.py", line 16, in good
    good.save()
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\db\models\base.py", line 814, in save
    self.save_base(
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\db\models\base.py", line 877, in save_base
    updated = self._save_table(
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\db\models\base.py", line 990, in _save_table
    updated = self._do_update(
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\db\models\base.py", line 1054, in _do_update
    return filtered._update(values) > 0
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\db\models\query.py", line 1231, in _update
    return query.get_compiler(self.db).execute_sql(CURSOR)
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1984, in execute_sql
    cursor = super().execute_sql(result_type)
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\db\backends\utils.py", line 102, in execute
    return super().execute(sql, params)
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
django.db.utils.IntegrityError: NOT NULL constraint failed: lesson4app_good.date_add
ERROR 2023-09-21 11:32:12,081 basehttp 4064 13872 "POST /lesson4/good/1 HTTP/1.1" 500 149486
INFO 2023-09-21 11:32:57,904 basehttp 4064 13872 "GET /lesson4/good/1 HTTP/1.1" 200 1099
INFO 2023-09-21 11:33:07,394 autoreload 4064 1104 C:\DEV\EDU\Django\myproject\lesson4app\views.py changed, reloading.
INFO 2023-09-21 11:33:08,095 autoreload 12072 7492 Watching for file changes with StatReloader
INFO 2023-09-21 11:33:10,987 basehttp 12072 6212 "GET /lesson4/good/1 HTTP/1.1" 200 1099
ERROR 2023-09-21 11:33:15,641 log 12072 6212 Internal Server Error: /lesson4/good/1
Traceback (most recent call last):
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
sqlite3.IntegrityError: NOT NULL constraint failed: lesson4app_good.date_add

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\DEV\EDU\Django\myproject\lesson4app\views.py", line 16, in good
    good.save()
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\db\models\base.py", line 814, in save
    self.save_base(
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\db\models\base.py", line 877, in save_base
    updated = self._save_table(
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\db\models\base.py", line 990, in _save_table
    updated = self._do_update(
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\db\models\base.py", line 1054, in _do_update
    return filtered._update(values) > 0
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\db\models\query.py", line 1231, in _update
    return query.get_compiler(self.db).execute_sql(CURSOR)
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1984, in execute_sql
    cursor = super().execute_sql(result_type)
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\db\backends\utils.py", line 102, in execute
    return super().execute(sql, params)
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
django.db.utils.IntegrityError: NOT NULL constraint failed: lesson4app_good.date_add
ERROR 2023-09-21 11:33:15,646 basehttp 12072 6212 "POST /lesson4/good/1 HTTP/1.1" 500 149486
INFO 2023-09-21 11:33:37,502 basehttp 12072 6212 "GET /lesson4/good/1 HTTP/1.1" 200 1099
INFO 2023-09-21 11:33:37,667 autoreload 12072 7492 C:\DEV\EDU\Django\myproject\lesson4app\views.py changed, reloading.
INFO 2023-09-21 11:33:38,335 autoreload 5248 17692 Watching for file changes with StatReloader
INFO 2023-09-21 11:34:03,949 autoreload 5248 17692 C:\DEV\EDU\Django\myproject\lesson4app\views.py changed, reloading.
INFO 2023-09-21 11:34:04,655 autoreload 2436 7592 Watching for file changes with StatReloader
INFO 2023-09-21 11:34:08,889 basehttp 2436 8872 "GET /lesson4/good/1 HTTP/1.1" 200 1099
ERROR 2023-09-21 11:34:13,446 log 2436 8872 Internal Server Error: /lesson4/good/1
Traceback (most recent call last):
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
sqlite3.IntegrityError: NOT NULL constraint failed: lesson4app_good.date_add

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\DEV\EDU\Django\myproject\lesson4app\views.py", line 15, in good_edit
    good.save()
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\db\models\base.py", line 814, in save
    self.save_base(
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\db\models\base.py", line 877, in save_base
    updated = self._save_table(
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\db\models\base.py", line 990, in _save_table
    updated = self._do_update(
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\db\models\base.py", line 1054, in _do_update
    return filtered._update(values) > 0
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\db\models\query.py", line 1231, in _update
    return query.get_compiler(self.db).execute_sql(CURSOR)
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1984, in execute_sql
    cursor = super().execute_sql(result_type)
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\db\backends\utils.py", line 102, in execute
    return super().execute(sql, params)
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
django.db.utils.IntegrityError: NOT NULL constraint failed: lesson4app_good.date_add
ERROR 2023-09-21 11:34:13,452 basehttp 2436 8872 "POST /lesson4/good/1 HTTP/1.1" 500 149511
INFO 2023-09-21 11:34:46,803 autoreload 2436 7592 C:\DEV\EDU\Django\myproject\lesson4app\views.py changed, reloading.
INFO 2023-09-21 11:34:47,665 autoreload 1816 15128 Watching for file changes with StatReloader
INFO 2023-09-21 11:34:51,291 basehttp 1816 17704 "GET /lesson4/good/1 HTTP/1.1" 200 1099
ERROR 2023-09-21 11:34:55,808 log 1816 17704 Internal Server Error: /lesson4/good/1
Traceback (most recent call last):
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
sqlite3.IntegrityError: NOT NULL constraint failed: lesson4app_good.date_add

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\DEV\EDU\Django\myproject\lesson4app\views.py", line 16, in good_edit
    good.save()
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\db\models\base.py", line 814, in save
    self.save_base(
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\db\models\base.py", line 877, in save_base
    updated = self._save_table(
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\db\models\base.py", line 990, in _save_table
    updated = self._do_update(
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\db\models\base.py", line 1054, in _do_update
    return filtered._update(values) > 0
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\db\models\query.py", line 1231, in _update
    return query.get_compiler(self.db).execute_sql(CURSOR)
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1984, in execute_sql
    cursor = super().execute_sql(result_type)
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\db\backends\utils.py", line 102, in execute
    return super().execute(sql, params)
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
django.db.utils.IntegrityError: NOT NULL constraint failed: lesson4app_good.date_add
ERROR 2023-09-21 11:34:55,812 basehttp 1816 17704 "POST /lesson4/good/1 HTTP/1.1" 500 149504
INFO 2023-09-21 11:35:24,421 autoreload 1816 15128 C:\DEV\EDU\Django\myproject\lesson4app\views.py changed, reloading.
INFO 2023-09-21 11:35:25,154 autoreload 11196 5704 Watching for file changes with StatReloader
INFO 2023-09-21 11:35:28,914 basehttp 11196 4304 "GET /lesson4/good/1 HTTP/1.1" 200 1099
ERROR 2023-09-21 11:35:32,182 log 11196 4304 Internal Server Error: /lesson4/good/1
Traceback (most recent call last):
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
sqlite3.IntegrityError: NOT NULL constraint failed: lesson4app_good.date_add

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\DEV\EDU\Django\myproject\lesson4app\views.py", line 16, in good_edit
    good.save()
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\db\models\base.py", line 814, in save
    self.save_base(
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\db\models\base.py", line 877, in save_base
    updated = self._save_table(
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\db\models\base.py", line 990, in _save_table
    updated = self._do_update(
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\db\models\base.py", line 1054, in _do_update
    return filtered._update(values) > 0
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\db\models\query.py", line 1231, in _update
    return query.get_compiler(self.db).execute_sql(CURSOR)
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1984, in execute_sql
    cursor = super().execute_sql(result_type)
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\db\backends\utils.py", line 102, in execute
    return super().execute(sql, params)
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
django.db.utils.IntegrityError: NOT NULL constraint failed: lesson4app_good.date_add
ERROR 2023-09-21 11:35:32,187 basehttp 11196 4304 "POST /lesson4/good/1 HTTP/1.1" 500 149501
INFO 2023-09-21 11:35:53,613 autoreload 11196 5704 C:\DEV\EDU\Django\myproject\lesson4app\views.py changed, reloading.
INFO 2023-09-21 11:35:54,346 autoreload 17620 11896 Watching for file changes with StatReloader
INFO 2023-09-21 11:35:59,415 basehttp 17620 11624 "GET /lesson4/good/1 HTTP/1.1" 200 1099
INFO 2023-09-21 11:36:51,057 autoreload 17620 11896 C:\DEV\EDU\Django\myproject\lesson4app\views.py changed, reloading.
INFO 2023-09-21 11:36:51,813 autoreload 13296 4588 Watching for file changes with StatReloader
INFO 2023-09-21 11:36:55,117 basehttp 13296 2860 "POST /lesson4/good/1 HTTP/1.1" 200 1100
INFO 2023-09-21 11:37:04,000 autoreload 13296 4588 C:\DEV\EDU\Django\myproject\lesson4app\views.py changed, reloading.
INFO 2023-09-21 11:37:04,733 autoreload 14380 11248 Watching for file changes with StatReloader
INFO 2023-09-21 11:37:07,795 basehttp 14380 14280 "GET /lesson4/good/1 HTTP/1.1" 200 1100
INFO 2023-09-21 11:37:13,333 basehttp 14380 14280 "POST /lesson4/good/1 HTTP/1.1" 200 1100
INFO 2023-09-21 11:37:40,163 autoreload 14380 11248 C:\DEV\EDU\Django\myproject\lesson4app\views.py changed, reloading.
INFO 2023-09-21 11:37:40,895 autoreload 17176 10660 Watching for file changes with StatReloader
INFO 2023-09-21 11:37:41,233 basehttp 17176 10832 "POST /lesson4/good/1 HTTP/1.1" 200 1100
INFO 2023-09-21 11:37:44,677 basehttp 17176 10832 "POST /lesson4/good/1 HTTP/1.1" 200 1099
INFO 2023-09-21 11:37:57,255 autoreload 17176 10660 C:\DEV\EDU\Django\myproject\lesson4app\views.py changed, reloading.
INFO 2023-09-21 11:37:57,974 autoreload 18340 14420 Watching for file changes with StatReloader
INFO 2023-09-21 11:39:44,596 autoreload 18340 14420 C:\DEV\EDU\Django\myproject\lesson4app\views.py changed, reloading.
INFO 2023-09-21 11:39:45,314 autoreload 2412 13768 Watching for file changes with StatReloader
INFO 2023-09-21 11:40:45,315 autoreload 2412 13768 C:\DEV\EDU\Django\myproject\lesson4app\forms.py changed, reloading.
INFO 2023-09-21 11:40:46,069 autoreload 15064 17856 Watching for file changes with StatReloader
ERROR 2023-09-21 11:40:48,805 log 15064 4216 Internal Server Error: /lesson4/good/1
Traceback (most recent call last):
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\DEV\EDU\Django\myproject\lesson4app\views.py", line 23, in good_edit
    request.POST, request.FILES, instance = request.user.userprofilemodel
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\utils\functional.py", line 268, in inner
    return func(_wrapped, *args)
AttributeError: 'AnonymousUser' object has no attribute 'userprofilemodel'
ERROR 2023-09-21 11:40:48,807 basehttp 15064 4216 "GET /lesson4/good/1 HTTP/1.1" 500 72261
INFO 2023-09-21 11:40:58,343 autoreload 15064 17856 C:\DEV\EDU\Django\myproject\lesson4app\views.py changed, reloading.
INFO 2023-09-21 11:40:59,072 autoreload 10452 16528 Watching for file changes with StatReloader
INFO 2023-09-21 11:41:01,643 basehttp 10452 12952 "GET /lesson4/good/1 HTTP/1.1" 200 1246
INFO 2023-09-21 11:42:48,607 autoreload 10452 16528 C:\DEV\EDU\Django\myproject\lesson4app\views.py changed, reloading.
INFO 2023-09-21 11:42:49,283 autoreload 6260 6816 Watching for file changes with StatReloader
INFO 2023-09-21 11:47:40,500 autoreload 6260 6816 C:\DEV\EDU\Django\myproject\lesson4app\views.py changed, reloading.
INFO 2023-09-21 11:47:41,240 autoreload 10800 17720 Watching for file changes with StatReloader
INFO 2023-09-21 11:47:44,633 basehttp 10800 15976 "GET /lesson4/good/1 HTTP/1.1" 200 1246
INFO 2023-09-21 11:48:09,313 basehttp 10800 15976 "POST /lesson4/good/1 HTTP/1.1" 200 1286
INFO 2023-09-21 11:48:40,486 basehttp 10800 15976 "POST /lesson4/good/1 HTTP/1.1" 200 1286
INFO 2023-09-21 11:52:14,412 autoreload 10800 17720 C:\DEV\EDU\Django\myproject\lesson4app\views.py changed, reloading.
INFO 2023-09-21 11:52:15,276 autoreload 12480 15136 Watching for file changes with StatReloader
ERROR 2023-09-21 11:52:18,702 log 12480 16964 Internal Server Error: /lesson4/good/1
Traceback (most recent call last):
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\DEV\EDU\Django\myproject\lesson4app\views.py", line 15, in good_edit
    fs.save(image.name, image)
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\core\files\storage\base.py", line 38, in save
    name = self._save(name, content)
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\core\files\storage\filesystem.py", line 110, in _save
    for chunk in content.chunks():
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\core\files\base.py", line 60, in chunks
    data = self.read(chunk_size)
PermissionError: [Errno 13] Permission denied
ERROR 2023-09-21 11:52:18,705 basehttp 12480 16964 "POST /lesson4/good/1 HTTP/1.1" 500 83292
INFO 2023-09-21 11:53:59,882 autoreload 9936 17748 Watching for file changes with StatReloader
INFO 2023-09-21 11:54:04,808 basehttp 9936 8200 "GET /lesson4/good/1 HTTP/1.1" 200 1247
ERROR 2023-09-21 11:54:09,909 log 9936 8200 Internal Server Error: /lesson4/good/1
Traceback (most recent call last):
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\DEV\EDU\Django\myproject\lesson4app\views.py", line 15, in good_edit
    fs.save(image.name, image)
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\core\files\storage\base.py", line 38, in save
    name = self._save(name, content)
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\core\files\storage\filesystem.py", line 110, in _save
    for chunk in content.chunks():
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\core\files\base.py", line 60, in chunks
    data = self.read(chunk_size)
PermissionError: [Errno 13] Permission denied
ERROR 2023-09-21 11:54:09,911 basehttp 9936 8200 "POST /lesson4/good/1 HTTP/1.1" 500 83303
INFO 2023-09-21 11:55:04,163 autoreload 4640 15488 Watching for file changes with StatReloader
INFO 2023-09-21 11:55:05,747 basehttp 4640 18224 "GET /lesson4/good/1 HTTP/1.1" 200 1247
ERROR 2023-09-21 11:55:09,350 log 4640 18224 Internal Server Error: /lesson4/good/1
Traceback (most recent call last):
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\DEV\EDU\Django\myproject\lesson4app\views.py", line 15, in good_edit
    fs.save(image.name, image)
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\core\files\storage\base.py", line 38, in save
    name = self._save(name, content)
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\core\files\storage\filesystem.py", line 110, in _save
    for chunk in content.chunks():
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\core\files\base.py", line 60, in chunks
    data = self.read(chunk_size)
PermissionError: [Errno 13] Permission denied
ERROR 2023-09-21 11:55:09,352 basehttp 4640 18224 "POST /lesson4/good/1 HTTP/1.1" 500 83303
INFO 2023-09-21 11:56:58,189 autoreload 4640 15488 C:\DEV\EDU\Django\myproject\myproject\settings.py changed, reloading.
INFO 2023-09-21 11:56:58,936 autoreload 17520 9936 Watching for file changes with StatReloader
INFO 2023-09-21 11:57:03,986 basehttp 17520 15528 "GET /lesson4/good/1 HTTP/1.1" 200 1247
INFO 2023-09-21 11:57:08,432 basehttp 17520 15528 "POST /lesson4/good/1 HTTP/1.1" 200 1286
INFO 2023-09-21 11:57:56,496 autoreload 17520 9936 C:\DEV\EDU\Django\myproject\lesson4app\models.py changed, reloading.
INFO 2023-09-21 11:57:57,199 autoreload 13356 11468 Watching for file changes with StatReloader
INFO 2023-09-21 11:58:10,877 autoreload 17628 6056 Watching for file changes with StatReloader
INFO 2023-09-21 11:58:18,508 basehttp 17628 17708 "GET /lesson4/good/1 HTTP/1.1" 200 1246
INFO 2023-09-21 11:58:39,132 autoreload 17628 6056 C:\DEV\EDU\Django\myproject\lesson4app\models.py changed, reloading.
INFO 2023-09-21 11:58:39,825 autoreload 17384 4636 Watching for file changes with StatReloader
INFO 2023-09-21 12:00:02,258 autoreload 13380 17708 Watching for file changes with StatReloader
INFO 2023-09-21 12:00:04,571 basehttp 13380 18264 "GET /lesson4/good/1 HTTP/1.1" 200 1247
INFO 2023-09-21 12:00:08,783 basehttp 13380 18264 "POST /lesson4/good/1 HTTP/1.1" 200 1286
INFO 2023-09-21 12:00:41,442 basehttp 13380 18264 "POST /lesson4/good/1 HTTP/1.1" 200 1286
INFO 2023-09-21 12:01:08,625 autoreload 13380 17708 C:\DEV\EDU\Django\myproject\lesson4app\views.py changed, reloading.
INFO 2023-09-21 12:01:09,294 autoreload 14200 13880 Watching for file changes with StatReloader
INFO 2023-09-21 12:01:11,854 basehttp 14200 2708 "POST /lesson4/good/1 HTTP/1.1" 200 1286
INFO 2023-09-21 12:01:29,849 autoreload 8376 17676 Watching for file changes with StatReloader
INFO 2023-09-21 12:01:35,070 basehttp 8376 2980 "GET /lesson4/good/1 HTTP/1.1" 200 1247
INFO 2023-09-21 12:01:40,196 basehttp 8376 2980 "POST /lesson4/good/1 HTTP/1.1" 200 1286
INFO 2023-09-21 12:03:11,513 autoreload 8376 17676 C:\DEV\EDU\Django\myproject\lesson4app\views.py changed, reloading.
INFO 2023-09-21 12:03:12,215 autoreload 5076 9956 Watching for file changes with StatReloader
INFO 2023-09-21 12:03:16,186 basehttp 5076 9264 "GET /lesson4/good/1 HTTP/1.1" 200 1247
INFO 2023-09-21 12:03:25,108 basehttp 5076 9264 "POST /lesson4/good/1 HTTP/1.1" 200 1286
INFO 2023-09-21 12:03:56,461 basehttp 5076 9264 "POST /lesson4/good/1 HTTP/1.1" 200 1286
INFO 2023-09-21 12:04:45,549 autoreload 5076 9956 C:\DEV\EDU\Django\myproject\lesson4app\models.py changed, reloading.
INFO 2023-09-21 12:04:46,295 autoreload 16396 7532 Watching for file changes with StatReloader
INFO 2023-09-21 12:05:04,620 autoreload 920 16880 Watching for file changes with StatReloader
INFO 2023-09-21 12:05:08,447 basehttp 920 17032 "GET /lesson4/good/1 HTTP/1.1" 200 1247
INFO 2023-09-21 12:05:13,102 basehttp 920 17032 "POST /lesson4/good/1 HTTP/1.1" 200 1286
INFO 2023-09-21 12:06:03,261 autoreload 920 16880 C:\DEV\EDU\Django\myproject\lesson4app\models.py changed, reloading.
INFO 2023-09-21 12:06:04,055 autoreload 7344 9960 Watching for file changes with StatReloader
INFO 2023-09-21 12:09:27,309 autoreload 17260 12476 Watching for file changes with StatReloader
INFO 2023-09-21 12:09:31,331 basehttp 17260 8028 "GET /lesson4/good/1 HTTP/1.1" 200 1286
INFO 2023-09-21 12:09:41,064 basehttp 17260 8028 "POST /lesson4/good/1 HTTP/1.1" 200 1286
WARNING 2023-09-21 12:09:55,536 log 17260 8028 Not Found: /media/1
WARNING 2023-09-21 12:09:55,537 basehttp 17260 8028 "GET /media/1 HTTP/1.1" 404 2645
INFO 2023-09-21 12:10:12,147 basehttp 17260 8028 "POST /lesson4/good/1 HTTP/1.1" 200 1286
INFO 2023-09-21 12:10:27,789 basehttp 17260 8028 "POST /lesson4/good/1 HTTP/1.1" 200 1286
INFO 2023-09-21 12:11:54,818 basehttp 17260 8028 "GET /lesson4/good/1 HTTP/1.1" 200 1316
INFO 2023-09-21 12:11:58,693 basehttp 17260 8028 "POST /lesson4/good/1 HTTP/1.1" 200 1316
INFO 2023-09-21 12:17:45,741 autoreload 17260 12476 C:\DEV\EDU\Django\myproject\lesson4app\views.py changed, reloading.
INFO 2023-09-21 12:17:46,564 autoreload 8748 10816 Watching for file changes with StatReloader
INFO 2023-09-21 12:18:42,747 basehttp 8748 16660 "GET /lesson4/good/1 HTTP/1.1" 200 1364
INFO 2023-09-21 12:19:13,839 autoreload 8748 10816 C:\DEV\EDU\Django\myproject\lesson4app\views.py changed, reloading.
INFO 2023-09-21 12:19:14,606 autoreload 464 11832 Watching for file changes with StatReloader
INFO 2023-09-21 12:19:17,156 autoreload 464 11832 C:\DEV\EDU\Django\myproject\lesson4app\views.py changed, reloading.
INFO 2023-09-21 12:19:18,031 autoreload 4640 436 Watching for file changes with StatReloader
INFO 2023-09-21 12:19:19,940 basehttp 4640 16552 "GET /lesson4/good/1 HTTP/1.1" 200 1390
WARNING 2023-09-21 12:19:20,009 log 4640 16552 Not Found: /media/uploads/mercury.png
WARNING 2023-09-21 12:19:20,009 basehttp 4640 16552 "GET /media/uploads/mercury.png HTTP/1.1" 404 2699
WARNING 2023-09-21 12:19:41,552 log 4640 16552 Not Found: /media/uploads/mercury.png
WARNING 2023-09-21 12:19:41,552 basehttp 4640 16552 "GET /media/uploads/mercury.png HTTP/1.1" 404 2699
WARNING 2023-09-21 12:20:04,219 log 4640 16552 Not Found: /media/uploads/mercury.png
WARNING 2023-09-21 12:20:04,220 basehttp 4640 16552 "GET /media/uploads/mercury.png HTTP/1.1" 404 2699
INFO 2023-09-21 12:20:56,660 autoreload 4640 436 C:\DEV\EDU\Django\myproject\lesson4app\urls.py changed, reloading.
INFO 2023-09-21 12:20:57,384 autoreload 13068 168 Watching for file changes with StatReloader
INFO 2023-09-21 12:21:07,183 autoreload 13068 168 C:\DEV\EDU\Django\myproject\lesson4app\urls.py changed, reloading.
INFO 2023-09-21 12:21:07,907 autoreload 1884 5972 Watching for file changes with StatReloader
INFO 2023-09-21 12:21:13,694 autoreload 1884 5972 C:\DEV\EDU\Django\myproject\lesson4app\urls.py changed, reloading.
INFO 2023-09-21 12:21:14,378 autoreload 11620 10728 Watching for file changes with StatReloader
INFO 2023-09-21 12:21:21,283 basehttp 11620 1148 "GET /lesson4/good/1 HTTP/1.1" 200 1390
WARNING 2023-09-21 12:21:21,317 log 11620 1148 Not Found: /media/uploads/mercury.png
WARNING 2023-09-21 12:21:21,321 basehttp 11620 1148 "GET /media/uploads/mercury.png HTTP/1.1" 404 2699
WARNING 2023-09-21 12:21:24,428 log 11620 1148 Not Found: /media/uploads/mercury.png
WARNING 2023-09-21 12:21:24,429 basehttp 11620 1148 "GET /media/uploads/mercury.png HTTP/1.1" 404 2699
INFO 2023-09-21 12:21:31,964 autoreload 5012 10496 Watching for file changes with StatReloader
INFO 2023-09-21 12:21:35,801 basehttp 5012 1164 "GET /lesson4/good/1 HTTP/1.1" 200 1390
WARNING 2023-09-21 12:21:35,831 log 5012 1164 Not Found: /media/uploads/mercury.png
WARNING 2023-09-21 12:21:35,839 basehttp 5012 1164 "GET /media/uploads/mercury.png HTTP/1.1" 404 2699
INFO 2023-09-21 12:25:00,308 autoreload 5012 10496 C:\DEV\EDU\Django\myproject\lesson4app\urls.py changed, reloading.
INFO 2023-09-21 12:25:01,058 autoreload 18240 15364 Watching for file changes with StatReloader
INFO 2023-09-21 12:25:04,394 basehttp 18240 13760 "GET /lesson4/good/1 HTTP/1.1" 200 1390
INFO 2023-09-21 12:25:04,473 basehttp 18240 13760 "GET /media/uploads/mercury.png HTTP/1.1" 200 180694
INFO 2023-09-21 12:25:14,795 basehttp 18240 13760 "POST /lesson4/good/1 HTTP/1.1" 200 1474
INFO 2023-09-21 12:25:14,826 basehttp 18240 13760 "GET /media/uploads/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA_%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0_2023-09-06_152506.png HTTP/1.1" 200 16017
INFO 2023-09-21 12:26:43,341 autoreload 18240 15364 C:\DEV\EDU\Django\myproject\lesson4app\forms.py changed, reloading.
INFO 2023-09-21 12:26:44,146 autoreload 16532 5992 Watching for file changes with StatReloader
INFO 2023-09-25 11:03:38,481 autoreload 2716 1408 Watching for file changes with StatReloader
INFO 2023-09-25 11:03:40,359 basehttp 2716 7080 "GET /admin HTTP/1.1" 301 0
INFO 2023-09-25 11:03:40,376 basehttp 2716 8988 "GET /admin/ HTTP/1.1" 302 0
INFO 2023-09-25 11:03:40,491 basehttp 2716 8988 "GET /admin/login/?next=/admin/ HTTP/1.1" 200 4181
INFO 2023-09-25 11:03:40,684 basehttp 2716 8988 "GET /static/admin/css/base.css HTTP/1.1" 200 21207
INFO 2023-09-25 11:03:40,688 basehttp 2716 8348 "GET /static/admin/css/dark_mode.css HTTP/1.1" 200 2929
INFO 2023-09-25 11:03:40,697 basehttp 2716 15012 "GET /static/admin/css/login.css HTTP/1.1" 200 958
INFO 2023-09-25 11:03:40,702 basehttp 2716 15516 "GET /static/admin/css/nav_sidebar.css HTTP/1.1" 200 2694
INFO 2023-09-25 11:03:40,707 basehttp 2716 12572 "GET /static/admin/css/responsive.css HTTP/1.1" 200 18533
INFO 2023-09-25 11:03:40,719 basehttp 2716 8348 "GET /static/admin/js/nav_sidebar.js HTTP/1.1" 200 3063
INFO 2023-09-25 11:03:40,731 basehttp 2716 16908 "GET /static/admin/js/theme.js HTTP/1.1" 200 1943
WARNING 2023-09-25 11:03:40,872 log 2716 16908 Not Found: /favicon.ico
WARNING 2023-09-25 11:03:40,873 basehttp 2716 16908 "GET /favicon.ico HTTP/1.1" 404 2783
INFO 2023-09-25 11:04:07,492 autoreload 2716 1408 C:\DEV\EDU\Django\myproject\myproject\settings.py changed, reloading.
INFO 2023-09-25 11:04:08,224 autoreload 15408 10108 Watching for file changes with StatReloader
INFO 2023-09-25 11:15:39,183 autoreload 7864 7880 Watching for file changes with StatReloader
INFO 2023-09-25 11:15:58,298 autoreload 7864 7880 C:\DEV\EDU\Django\myproject\lesson5app\admin.py changed, reloading.
INFO 2023-09-25 11:15:58,999 autoreload 7928 12172 Watching for file changes with StatReloader
INFO 2023-09-25 11:18:40,481 autoreload 7928 12172 C:\DEV\EDU\Django\myproject\lesson5app\admin.py changed, reloading.
INFO 2023-09-25 11:18:41,226 autoreload 4892 12456 Watching for file changes with StatReloader
INFO 2023-09-25 11:19:23,352 autoreload 4892 12456 C:\DEV\EDU\Django\myproject\lesson5app\admin.py changed, reloading.
INFO 2023-09-25 11:19:24,040 autoreload 6316 8504 Watching for file changes with StatReloader
INFO 2023-09-25 11:21:45,866 autoreload 6316 8504 C:\DEV\EDU\Django\myproject\lesson5app\admin.py changed, reloading.
INFO 2023-09-25 11:21:46,566 autoreload 7616 16632 Watching for file changes with StatReloader
INFO 2023-09-25 11:22:02,574 autoreload 7616 16632 C:\DEV\EDU\Django\myproject\lesson5app\admin.py changed, reloading.
INFO 2023-09-25 11:22:03,237 autoreload 10176 1532 Watching for file changes with StatReloader
INFO 2023-09-25 11:22:30,822 autoreload 10176 1532 C:\DEV\EDU\Django\myproject\lesson5app\admin.py changed, reloading.
INFO 2023-09-25 11:22:31,434 autoreload 11444 9172 Watching for file changes with StatReloader
INFO 2023-09-25 11:23:21,254 autoreload 11444 9172 C:\DEV\EDU\Django\myproject\lesson5app\admin.py changed, reloading.
INFO 2023-09-25 11:23:21,904 autoreload 8372 17192 Watching for file changes with StatReloader
INFO 2023-09-25 11:23:30,622 basehttp 8372 11516 "GET /admin/login/?next=/admin/ HTTP/1.1" 200 4267
INFO 2023-09-25 11:24:31,120 basehttp 8372 11516 "POST /admin/login/?next=/admin/ HTTP/1.1" 200 4534
INFO 2023-09-25 11:24:35,891 basehttp 8372 11516 "POST /admin/login/?next=/admin/ HTTP/1.1" 302 0
INFO 2023-09-25 11:24:35,931 basehttp 8372 11516 "GET /admin/ HTTP/1.1" 200 7457
INFO 2023-09-25 11:24:36,004 basehttp 8372 11516 "GET /static/admin/css/dashboard.css HTTP/1.1" 200 441
INFO 2023-09-25 11:24:36,019 basehttp 8372 11516 "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 200 331
INFO 2023-09-25 11:24:36,019 basehttp 8372 7800 "GET /static/admin/img/icon-changelink.svg HTTP/1.1" 200 380
INFO 2023-09-25 11:24:39,930 basehttp 8372 7800 "GET /admin/lesson5app/order/ HTTP/1.1" 200 9438
INFO 2023-09-25 11:24:39,969 basehttp 8372 7800 "GET /static/admin/css/changelists.css HTTP/1.1" 200 6566
INFO 2023-09-25 11:24:39,973 basehttp 8372 11516 "GET /admin/jsi18n/ HTTP/1.1" 200 16066
INFO 2023-09-25 11:24:40,005 basehttp 8372 7800 "GET /static/admin/js/urlify.js HTTP/1.1" 200 7887
INFO 2023-09-25 11:24:40,006 basehttp 8372 11516 "GET /static/admin/js/actions.js HTTP/1.1" 200 7872
INFO 2023-09-25 11:24:40,009 basehttp 8372 16300 "GET /static/admin/js/jquery.init.js HTTP/1.1" 200 347
INFO 2023-09-25 11:24:40,024 basehttp 8372 7800 "GET /static/admin/js/prepopulate.js HTTP/1.1" 200 1531
INFO 2023-09-25 11:24:40,034 basehttp 8372 16068 "GET /static/admin/js/core.js HTTP/1.1" 200 5682
INFO 2023-09-25 11:24:40,036 basehttp 8372 13904 "GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 200 8943
INFO 2023-09-25 11:24:40,063 basehttp 8372 7860 "GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 200 292458
INFO 2023-09-25 11:24:40,087 basehttp 8372 7860 "GET /static/admin/js/filters.js HTTP/1.1" 200 978
INFO 2023-09-25 11:24:40,100 basehttp 8372 11516 "GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 200 232381
INFO 2023-09-25 11:24:40,123 basehttp 8372 11516 "GET /static/admin/img/tooltag-add.svg HTTP/1.1" 200 331
INFO 2023-09-25 11:24:43,529 basehttp 8372 11516 "GET /admin/lesson5app/client/ HTTP/1.1" 200 9855
INFO 2023-09-25 11:24:43,555 basehttp 8372 11516 "GET /admin/jsi18n/ HTTP/1.1" 200 16066
INFO 2023-09-25 11:24:43,559 basehttp 8372 7860 "GET /static/admin/img/search.svg HTTP/1.1" 200 458
INFO 2023-09-25 11:24:45,222 basehttp 8372 7860 "GET /admin/lesson5app/client/add/ HTTP/1.1" 200 11304
INFO 2023-09-25 11:24:45,252 basehttp 8372 13904 "GET /admin/jsi18n/ HTTP/1.1" 200 16066
INFO 2023-09-25 11:24:45,256 basehttp 8372 7860 "GET /static/admin/css/forms.css HTTP/1.1" 200 9047
INFO 2023-09-25 11:24:45,274 basehttp 8372 11516 "GET /static/admin/js/prepopulate_init.js HTTP/1.1" 200 586
INFO 2023-09-25 11:24:45,280 basehttp 8372 7860 "GET /static/admin/css/widgets.css HTTP/1.1" 200 11900
INFO 2023-09-25 11:24:45,298 basehttp 8372 11516 "GET /static/admin/js/change_form.js HTTP/1.1" 200 606
INFO 2023-09-25 11:24:51,337 basehttp 8372 11516 "POST /admin/lesson5app/client/add/ HTTP/1.1" 200 11565
INFO 2023-09-25 11:24:51,364 basehttp 8372 11516 "GET /admin/jsi18n/ HTTP/1.1" 200 16066
INFO 2023-09-25 11:24:55,923 basehttp 8372 11516 "POST /admin/lesson5app/client/add/ HTTP/1.1" 200 11572
INFO 2023-09-25 11:24:55,956 basehttp 8372 11516 "GET /admin/jsi18n/ HTTP/1.1" 200 16066
INFO 2023-09-25 11:25:01,947 basehttp 8372 11516 "POST /admin/lesson5app/client/add/ HTTP/1.1" 302 0
INFO 2023-09-25 11:25:01,993 basehttp 8372 11516 "GET /admin/lesson5app/client/ HTTP/1.1" 200 12033
INFO 2023-09-25 11:25:02,021 basehttp 8372 11516 "GET /admin/jsi18n/ HTTP/1.1" 200 16066
INFO 2023-09-25 11:25:02,066 basehttp 8372 11516 "GET /static/admin/img/icon-yes.svg HTTP/1.1" 200 436
INFO 2023-09-25 11:25:02,078 basehttp 8372 7860 "GET /static/admin/img/sorting-icons.svg HTTP/1.1" 200 1097
ERROR 2023-09-25 11:25:04,838 log 8372 7860 Internal Server Error: /admin/lesson5app/good/add/
Traceback (most recent call last):
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\contrib\admin\options.py", line 809, in get_form
    return modelform_factory(self.model, **defaults)
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\forms\models.py", line 642, in modelform_factory
    return type(form)(class_name, (form,), form_class_attrs)
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\forms\models.py", line 321, in __new__
    raise FieldError(message)
django.core.exceptions.FieldError: Unknown field(s) (date_added) specified for Good

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\contrib\admin\options.py", line 688, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\utils\decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\views\decorators\cache.py", line 62, in _wrapper_view_func
    response = view_func(request, *args, **kwargs)
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\contrib\admin\sites.py", line 242, in inner
    return view(request, *args, **kwargs)
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\contrib\admin\options.py", line 1886, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\utils\decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\utils\decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\contrib\admin\options.py", line 1747, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\contrib\admin\options.py", line 1782, in _changeform_view
    ModelForm = self.get_form(
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\contrib\admin\options.py", line 811, in get_form
    raise FieldError(
django.core.exceptions.FieldError: Unknown field(s) (date_added) specified for Good. Check fields/fieldsets/exclude attributes of class GoodAdmin.
ERROR 2023-09-25 11:25:04,843 basehttp 8372 7860 "GET /admin/lesson5app/good/add/ HTTP/1.1" 500 133749
INFO 2023-09-25 11:25:19,231 autoreload 8372 17192 C:\DEV\EDU\Django\myproject\lesson5app\admin.py changed, reloading.
INFO 2023-09-25 11:25:19,956 autoreload 4372 18192 Watching for file changes with StatReloader
INFO 2023-09-25 11:25:21,453 basehttp 4372 17292 "GET /admin/lesson5app/good/add/ HTTP/1.1" 200 12157
INFO 2023-09-25 11:25:21,501 basehttp 4372 18328 "GET /admin/jsi18n/ HTTP/1.1" 200 16066
INFO 2023-09-25 11:25:21,537 basehttp 4372 17292 "GET /static/admin/js/collapse.js HTTP/1.1" 200 1803
INFO 2023-09-25 11:25:28,192 basehttp 4372 17292 "POST /admin/lesson5app/good/add/ HTTP/1.1" 200 12351
INFO 2023-09-25 11:25:28,222 basehttp 4372 17292 "GET /admin/jsi18n/ HTTP/1.1" 200 16066
INFO 2023-09-25 11:25:30,694 basehttp 4372 17292 "POST /admin/lesson5app/good/add/ HTTP/1.1" 302 0
INFO 2023-09-25 11:25:30,737 basehttp 4372 17292 "GET /admin/lesson5app/good/ HTTP/1.1" 200 12323
INFO 2023-09-25 11:25:30,767 basehttp 4372 17292 "GET /admin/jsi18n/ HTTP/1.1" 200 16066
INFO 2023-09-25 11:25:34,064 basehttp 4372 17292 "GET /admin/lesson5app/good/1/change/ HTTP/1.1" 200 12479
INFO 2023-09-25 11:25:34,095 basehttp 4372 17292 "GET /admin/jsi18n/ HTTP/1.1" 200 16066
INFO 2023-09-25 11:25:44,866 basehttp 4372 17292 "GET /admin/lesson5app/order/add/ HTTP/1.1" 200 12588
INFO 2023-09-25 11:25:44,894 basehttp 4372 17292 "GET /admin/jsi18n/ HTTP/1.1" 200 16066
INFO 2023-09-25 11:25:44,903 basehttp 4372 18328 "GET /static/admin/img/icon-viewlink.svg HTTP/1.1" 200 581
INFO 2023-09-25 11:25:56,533 basehttp 4372 18328 "GET /admin/lesson5app/good/add/?_to_field=id&_popup=1 HTTP/1.1" 200 7332
INFO 2023-09-25 11:25:56,623 basehttp 4372 18328 "GET /admin/jsi18n/ HTTP/1.1" 200 16066
INFO 2023-09-25 11:26:02,621 basehttp 4372 18328 "GET /admin/lesson5app/good/add/?_to_field=id&_popup=1 HTTP/1.1" 200 7332
INFO 2023-09-25 11:26:02,663 basehttp 4372 18328 "GET /admin/jsi18n/ HTTP/1.1" 200 16066
INFO 2023-09-25 11:26:09,917 basehttp 4372 18328 "POST /admin/lesson5app/good/add/?_to_field=id&_popup=1 HTTP/1.1" 200 376
INFO 2023-09-25 11:26:09,946 basehttp 4372 18328 "GET /static/admin/js/popup_response.js HTTP/1.1" 200 551
ERROR 2023-09-25 11:26:18,696 log 4372 18328 Internal Server Error: /admin/lesson5app/order/add/
Traceback (most recent call last):
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
sqlite3.IntegrityError: NOT NULL constraint failed: lesson5app_order.total

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\contrib\admin\options.py", line 688, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\utils\decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\views\decorators\cache.py", line 62, in _wrapper_view_func
    response = view_func(request, *args, **kwargs)
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\contrib\admin\sites.py", line 242, in inner
    return view(request, *args, **kwargs)
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\contrib\admin\options.py", line 1886, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\utils\decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\utils\decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\contrib\admin\options.py", line 1747, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\contrib\admin\options.py", line 1798, in _changeform_view
    self.save_model(request, new_object, form, not add)
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\contrib\admin\options.py", line 1227, in save_model
    obj.save()
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\db\models\base.py", line 814, in save
    self.save_base(
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\db\models\base.py", line 877, in save_base
    updated = self._save_table(
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\db\models\base.py", line 1020, in _save_table
    results = self._do_insert(
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\db\models\base.py", line 1061, in _do_insert
    return manager._insert(
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\db\models\query.py", line 1805, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1822, in execute_sql
    cursor.execute(sql, params)
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\db\backends\utils.py", line 102, in execute
    return super().execute(sql, params)
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
django.db.utils.IntegrityError: NOT NULL constraint failed: lesson5app_order.total
ERROR 2023-09-25 11:26:18,716 basehttp 4372 18328 "POST /admin/lesson5app/order/add/ HTTP/1.1" 500 191618
INFO 2023-09-25 11:26:42,219 autoreload 4372 18192 C:\DEV\EDU\Django\myproject\lesson5app\admin.py changed, reloading.
INFO 2023-09-25 11:26:42,992 autoreload 14512 9516 Watching for file changes with StatReloader
INFO 2023-09-25 11:26:44,568 basehttp 14512 9244 "GET /admin/lesson5app/order/add/ HTTP/1.1" 200 12706
INFO 2023-09-25 11:26:44,611 basehttp 14512 9244 "GET /admin/jsi18n/ HTTP/1.1" 200 16066
INFO 2023-09-25 11:26:52,763 basehttp 14512 9244 "POST /admin/lesson5app/order/add/ HTTP/1.1" 302 0
INFO 2023-09-25 11:26:52,800 basehttp 14512 9244 "GET /admin/lesson5app/order/ HTTP/1.1" 200 11677
INFO 2023-09-25 11:26:52,830 basehttp 14512 9244 "GET /admin/jsi18n/ HTTP/1.1" 200 16066
INFO 2023-09-25 11:26:59,154 basehttp 14512 9244 "GET /admin/lesson5app/order/ HTTP/1.1" 200 11459
INFO 2023-09-25 11:26:59,179 basehttp 14512 9244 "GET /admin/jsi18n/ HTTP/1.1" 200 16066
INFO 2023-09-25 11:27:14,730 basehttp 14512 9244 "GET /admin/lesson5app/order/1/change/ HTTP/1.1" 200 12968
INFO 2023-09-25 11:27:14,761 basehttp 14512 9244 "GET /admin/jsi18n/ HTTP/1.1" 200 16066
INFO 2023-09-25 11:29:29,277 autoreload 14512 9516 C:\DEV\EDU\Django\myproject\lesson5app\admin.py changed, reloading.
INFO 2023-09-25 11:29:30,083 autoreload 1908 12420 Watching for file changes with StatReloader
INFO 2023-09-25 11:29:33,334 basehttp 1908 13988 "GET /admin/lesson5app/order/ HTTP/1.1" 200 11459
INFO 2023-09-25 11:29:33,365 basehttp 1908 13988 "GET /admin/jsi18n/ HTTP/1.1" 200 16066
ERROR 2023-09-25 11:29:40,499 log 1908 13988 Internal Server Error: /admin/lesson5app/order/1/change/
Traceback (most recent call last):
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\contrib\admin\options.py", line 809, in get_form
    return modelform_factory(self.model, **defaults)
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\forms\models.py", line 642, in modelform_factory
    return type(form)(class_name, (form,), form_class_attrs)
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\forms\models.py", line 321, in __new__
    raise FieldError(message)
django.core.exceptions.FieldError: Unknown field(s) (get_good) specified for Order

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\contrib\admin\options.py", line 688, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\utils\decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\views\decorators\cache.py", line 62, in _wrapper_view_func
    response = view_func(request, *args, **kwargs)
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\contrib\admin\sites.py", line 242, in inner
    return view(request, *args, **kwargs)
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\contrib\admin\options.py", line 1889, in change_view
    return self.changeform_view(request, object_id, form_url, extra_context)
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\utils\decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\utils\decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\contrib\admin\options.py", line 1747, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\contrib\admin\options.py", line 1782, in _changeform_view
    ModelForm = self.get_form(
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\contrib\admin\options.py", line 811, in get_form
    raise FieldError(
django.core.exceptions.FieldError: Unknown field(s) (get_good) specified for Order. Check fields/fieldsets/exclude attributes of class OrderAdmin.
ERROR 2023-09-25 11:29:40,503 basehttp 1908 13988 "GET /admin/lesson5app/order/1/change/ HTTP/1.1" 500 133608
INFO 2023-09-25 11:30:34,091 autoreload 1908 12420 C:\DEV\EDU\Django\myproject\lesson5app\admin.py changed, reloading.
INFO 2023-09-25 11:30:34,818 autoreload 10724 6572 Watching for file changes with StatReloader
ERROR 2023-09-25 11:30:37,262 log 10724 4580 Internal Server Error: /admin/lesson5app/order/1/change/
Traceback (most recent call last):
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\contrib\admin\options.py", line 809, in get_form
    return modelform_factory(self.model, **defaults)
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\forms\models.py", line 642, in modelform_factory
    return type(form)(class_name, (form,), form_class_attrs)
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\forms\models.py", line 321, in __new__
    raise FieldError(message)
django.core.exceptions.FieldError: Unknown field(s) (get_good) specified for Order

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\contrib\admin\options.py", line 688, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\utils\decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\views\decorators\cache.py", line 62, in _wrapper_view_func
    response = view_func(request, *args, **kwargs)
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\contrib\admin\sites.py", line 242, in inner
    return view(request, *args, **kwargs)
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\contrib\admin\options.py", line 1889, in change_view
    return self.changeform_view(request, object_id, form_url, extra_context)
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\utils\decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\utils\decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\contrib\admin\options.py", line 1747, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\contrib\admin\options.py", line 1782, in _changeform_view
    ModelForm = self.get_form(
  File "C:\DEV\EDU\Django\venv\lib\site-packages\django\contrib\admin\options.py", line 811, in get_form
    raise FieldError(
django.core.exceptions.FieldError: Unknown field(s) (get_good) specified for Order. Check fields/fieldsets/exclude attributes of class OrderAdmin.
ERROR 2023-09-25 11:30:37,268 basehttp 10724 4580 "GET /admin/lesson5app/order/1/change/ HTTP/1.1" 500 133745
INFO 2023-09-25 11:31:22,059 autoreload 10724 6572 C:\DEV\EDU\Django\myproject\lesson5app\admin.py changed, reloading.
INFO 2023-09-25 11:31:22,798 autoreload 14800 10436 Watching for file changes with StatReloader
INFO 2023-09-25 11:31:26,558 basehttp 14800 13876 "GET /admin/lesson5app/order/1/change/ HTTP/1.1" 200 12968
INFO 2023-09-25 11:31:26,591 basehttp 14800 13876 "GET /admin/jsi18n/ HTTP/1.1" 200 16066
INFO 2023-09-25 11:31:28,837 basehttp 14800 13876 "GET /admin/lesson5app/order/ HTTP/1.1" 200 11630
INFO 2023-09-25 11:31:28,867 basehttp 14800 13876 "GET /admin/jsi18n/ HTTP/1.1" 200 16066
INFO 2023-09-25 11:31:31,762 basehttp 14800 13876 "GET /admin/lesson5app/order/1/change/ HTTP/1.1" 200 12968
INFO 2023-09-25 11:31:31,793 basehttp 14800 13876 "GET /admin/jsi18n/ HTTP/1.1" 200 16066
INFO 2023-09-25 11:31:41,572 autoreload 14800 10436 C:\DEV\EDU\Django\myproject\lesson5app\admin.py changed, reloading.
INFO 2023-09-25 11:31:42,356 autoreload 7296 4996 Watching for file changes with StatReloader
INFO 2023-09-25 11:32:00,609 basehttp 7296 10556 "GET /admin/lesson5app/order/1/change/ HTTP/1.1" 200 12968
INFO 2023-09-25 11:32:00,635 basehttp 7296 10556 "GET /admin/jsi18n/ HTTP/1.1" 200 16066
INFO 2023-09-25 11:32:02,052 basehttp 7296 10556 "GET /admin/lesson5app/client/ HTTP/1.1" 200 11777
INFO 2023-09-25 11:32:02,084 basehttp 7296 10556 "GET /admin/jsi18n/ HTTP/1.1" 200 16066
INFO 2023-09-25 11:32:03,355 basehttp 7296 10556 "GET /admin/lesson5app/good/ HTTP/1.1" 200 12439
INFO 2023-09-25 11:32:03,378 basehttp 7296 10556 "GET /admin/jsi18n/ HTTP/1.1" 200 16066
INFO 2023-09-25 11:32:03,928 basehttp 7296 10556 "GET /admin/lesson5app/order/ HTTP/1.1" 200 11459
INFO 2023-09-25 11:32:03,954 basehttp 7296 10556 "GET /admin/jsi18n/ HTTP/1.1" 200 16066
INFO 2023-09-25 11:32:17,393 basehttp 7296 10556 "GET /admin/lesson5app/client/ HTTP/1.1" 200 11777
INFO 2023-09-25 11:32:17,422 basehttp 7296 10556 "GET /admin/jsi18n/ HTTP/1.1" 200 16066
INFO 2023-09-25 11:32:18,574 basehttp 7296 10556 "GET /admin/lesson5app/good/ HTTP/1.1" 200 12439
INFO 2023-09-25 11:32:18,600 basehttp 7296 10556 "GET /admin/jsi18n/ HTTP/1.1" 200 16066
INFO 2023-09-25 11:32:19,222 basehttp 7296 10556 "GET /admin/lesson5app/order/ HTTP/1.1" 200 11459
INFO 2023-09-25 11:32:19,245 basehttp 7296 10556 "GET /admin/jsi18n/ HTTP/1.1" 200 16066
INFO 2023-09-25 11:58:57,496 autoreload 7296 4996 C:\DEV\EDU\Django\myproject\lesson5app\admin.py changed, reloading.
